### ISSUE TITLE
Implement link count in adjacency to natively support multiple parallel links

### ISSUE THREAD

**Issue by networmix** [networmix/NetGraph#58]
Avoid this:

```
  adjacency:
    - source: my_clos1/spine
      target: my_clos2/spine
      pattern: one_to_one
      link_params:
        capacity: 1
        cost: 1
    - source: my_clos1/spine
      target: my_clos2/spine
      pattern: one_to_one
      link_params:
        capacity: 1
        cost: 1
    - source: my_clos1/spine
      target: my_clos2/spine
      pattern: one_to_one
      link_params:
        capacity: 1
        cost: 1
    - source: my_clos1/spine
      target: my_clos2/spine
      pattern: one_to_one
      link_params:
        capacity: 1
        cost: 1
```

Allow this:
```
  adjacency:
    - source: my_clos1/spine
      target: my_clos2/spine
      pattern: one_to_one
      link_count: 4
      link_params:
        capacity: 1
        cost: 1
```
